<?php
use App\Core\Csrf;
$typeLabels=['IRREGULARITY'=>'Irregularidade','WARNING'=>'Advertência','ADJUSTMENT'=>'Adequação','SUSPENSION'=>'Suspensão','EMBARGO'=>'Embargo','RELEASE'=>'Liberação'];
$statusLabels=['DRAFT'=>'Rascunho','ISSUED'=>'Emitida','DELIVERED'=>'Entregue','RESOLVED'=>'Resolvida','CANCELLED'=>'Cancelada'];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Notificações · Unidade <?=htmlspecialchars($work['unit'])?></title><link rel="stylesheet" href="/assets/css/app.css"></head><body class="app-body"><div class="shell">
<aside class="sidebar"><div class="brand">Fiscaliza Obras</div><nav><a href="/">Visão geral</a><a href="/works?condo=<?=(int)$work['condominium_id']?>">Obras</a><a href="/work?id=<?=(int)$work['id']?>">Detalhes da obra</a><a class="active" href="/notifications?work=<?=(int)$work['id']?>">Notificações</a></nav></aside>
<main class="content"><header class="topbar"><div><p class="eyebrow"><?=htmlspecialchars($work['condominium_name'])?></p><h1>Notificações · Unidade <?=htmlspecialchars($work['unit'])?></h1><p class="muted">Controle de entrega, resolução e cancelamento dos comunicados formais.</p></div><a class="button secondary" href="/work?id=<?=(int)$work['id']?>">← Voltar à obra</a></header>
<?php if(isset($_GET['updated'])):?><div class="alert success">Status da notificação atualizado.</div><?php endif;?>
<section class="panel"><div class="panel-header"><div><h2>Notificações emitidas</h2><p><?=count($notifications)?> registro(s).</p></div></div><div class="operation-list">
<?php if(!$notifications):?><div class="empty-state"><p>Nenhuma notificação emitida para esta obra.</p></div><?php endif;?>
<?php foreach($notifications as $n):$activeRestriction=in_array($n['type'],['SUSPENSION','EMBARGO'],true)&&in_array($work['status'],['SUSPENDED','EMBARGOED'],true);?><article class="operation-card"><div><div class="row-gap"><strong><?=htmlspecialchars($typeLabels[$n['type']]??$n['type'])?> · <?=htmlspecialchars($n['number'])?></strong><span class="badge"><?=htmlspecialchars($statusLabels[$n['status']]??$n['status'])?></span></div><small><?=htmlspecialchars($n['creator_name'])?> · <?=htmlspecialchars($n['issued_at']?:$n['created_at'])?></small><p><b><?=htmlspecialchars($n['reason'])?></b></p><p><?=nl2br(htmlspecialchars($n['body']))?></p><?php if($n['deadline']):?><p><b>Prazo:</b> <?=htmlspecialchars(date('d/m/Y H:i',strtotime($n['deadline'])))?></p><?php endif;?><?php if($activeRestriction):?><div class="review-note">A suspensão/embargo permanece ativo. Emita uma Liberação antes de encerrar esta notificação.</div><?php endif;?></div><div class="inline-actions"><a class="button secondary" target="_blank" href="/notification/pdf?id=<?=(int)$n['id']?>">PDF</a>
<?php if($canInspect&&$n['status']==='ISSUED'):?><form method="post" action="/work/notification/status"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="notification_id" value="<?=(int)$n['id']?>"><input type="hidden" name="target_status" value="DELIVERED"><button class="button secondary">Marcar entregue</button></form><?php endif;?>
<?php if($canInspect&&in_array($n['status'],['ISSUED','DELIVERED'],true)&&!$activeRestriction):?><form method="post" action="/work/notification/status"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="notification_id" value="<?=(int)$n['id']?>"><input type="hidden" name="target_status" value="RESOLVED"><button class="button primary">Resolver</button></form><?php endif;?>
<?php if($canManage&&in_array($n['status'],['ISSUED','DELIVERED'],true)&&!$activeRestriction):?><form method="post" action="/work/notification/status"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="notification_id" value="<?=(int)$n['id']?>"><input type="hidden" name="target_status" value="CANCELLED"><button class="button danger">Cancelar</button></form><?php endif;?>
</div></article><?php endforeach;?></div></section></main></div></body></html>
