<?php
use App\Core\Csrf;
$statusLabels = [
    'DRAFT'=>'Rascunho','WAITING_DOCUMENTS'=>'Aguardando documentos','UNDER_REVIEW'=>'Em análise','CORRECTION_REQUIRED'=>'Correção necessária','TECHNICALLY_APPROVED'=>'Aprovada tecnicamente','AUTHORIZED'=>'Autorizada','IN_PROGRESS'=>'Em andamento','NOTIFIED'=>'Notificada','SUSPENDED'=>'Suspensa','EMBARGOED'=>'Embargada','COMPLETION_INSPECTION'=>'Vistoria de conclusão','COMPLETED'=>'Concluída','CANCELLED'=>'Cancelada',
];
$documentLabels=['SUBMITTED'=>'Em análise','APPROVED'=>'Aprovado','CORRECTION_REQUIRED'=>'Corrigir','REJECTED'=>'Reprovado','PENDING'=>'Pendente'];
$severityLabels=['LOW'=>'Leve','MEDIUM'=>'Moderada','HIGH'=>'Grave','CRITICAL'=>'Crítica'];
$typeLabels=['IRREGULARITY'=>'Irregularidade','WARNING'=>'Advertência','ADJUSTMENT'=>'Adequação','SUSPENSION'=>'Suspensão','EMBARGO'=>'Embargo','RELEASE'=>'Liberação'];
$phaseMap=[
'DRAFT'=>0,'WAITING_DOCUMENTS'=>0,'UNDER_REVIEW'=>1,'CORRECTION_REQUIRED'=>1,'TECHNICALLY_APPROVED'=>2,'AUTHORIZED'=>3,'IN_PROGRESS'=>4,'NOTIFIED'=>4,'SUSPENDED'=>4,'EMBARGOED'=>4,'COMPLETION_INSPECTION'=>5,'COMPLETED'=>6,'CANCELLED'=>0,
];
$currentPhase=$phaseMap[$work['status']]??0;
$steps=['Documentos','Análise','Aprovação técnica','Autorização','Execução','Vistoria final','Concluída'];
$isRestricted=in_array($work['status'],['SUSPENDED','EMBARGOED'],true);
$attentionTotal=$documentPending+$documentCorrection+$openCorrections+$activeNotifications;
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Minha obra · Unidade <?=htmlspecialchars($work['unit'])?></title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/ui-v2.css"><style>.responsible-progress{display:grid;grid-template-columns:repeat(7,1fr);gap:6px;margin-top:14px}.responsible-step{position:relative;text-align:center;padding:9px 5px;border-radius:8px;background:#f2f4f7;color:#667085;font-size:10px;font-weight:700}.responsible-step.done{background:#ecfdf3;color:#027a48}.responsible-step.current{background:#eff4ff;color:#175cd3;box-shadow:inset 0 0 0 1px #84adff}.responsible-attention{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.responsible-attention span{padding:6px 9px;border-radius:999px;background:#fff4ed;color:#c4320a;font-size:11px;font-weight:700}.responsible-attention .ok{background:#ecfdf3;color:#027a48}.portal-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}@media(max-width:760px){.responsible-progress{grid-template-columns:1fr}.responsible-step{text-align:left}.portal-actions>.button{width:100%;text-align:center}}</style></head>
<body class="app-body"><div class="shell">
<aside class="sidebar"><div class="brand">Fiscaliza Obras</div><nav><a href="/responsible">Minhas obras</a><a class="active" href="#resumo">Resumo</a><a href="#documentos">Documentos</a><a href="#correcoes">Correções</a><a href="#notificacoes">Notificações</a><a href="/work/diary?id=<?=(int)$work['id']?>">Diário da obra</a><a href="#conclusao">Conclusão</a></nav><form method="post" action="/logout" style="margin-top:24px"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><button class="button secondary" type="submit">Sair</button></form></aside>
<main class="content"><header class="topbar"><div><p class="eyebrow"><?=htmlspecialchars($work['condominium_name'])?></p><h1>Unidade <?=htmlspecialchars($work['unit'])?></h1><p class="muted"><?=htmlspecialchars($work['work_type'] ?: 'Obra')?> · <?=htmlspecialchars($statusLabels[$work['status']] ?? $work['status'])?></p></div><a class="button secondary" href="/responsible">← Minhas obras</a></header>
<?php if(isset($_GET['access'])):?><div class="alert success">Acesso ativado. Esta é a área de acompanhamento da sua obra.</div><?php endif;?>
<?php if(isset($_GET['uploaded'])):?><div class="alert success">Documento enviado com sucesso.</div><?php endif;?>
<?php if($isRestricted):?><div class="alert error"><strong>Obra <?=htmlspecialchars(mb_strtolower($statusLabels[$work['status']]))?>.</strong> Consulte as notificações abaixo e regularize as pendências antes de prosseguir.</div><?php endif;?>
<section class="panel" id="resumo"><div class="panel-header"><div><h2>Acompanhamento da sua obra</h2><p>Status do processo e itens que precisam da sua atenção.</p></div><span class="badge"><?=htmlspecialchars($statusLabels[$work['status']] ?? $work['status'])?></span></div>
<div class="responsible-progress"><?php foreach($steps as $idx=>$step):?><div class="responsible-step <?=$idx<$currentPhase?'done':($idx===$currentPhase?'current':'')?>"><?=htmlspecialchars($step)?></div><?php endforeach;?></div>
<div class="info-grid" style="margin-top:18px"><div><small>Documentos obrigatórios não enviados</small><strong><?=(int)$documentPending?></strong></div><div><small>Documentos para corrigir</small><strong><?=(int)$documentCorrection?></strong></div><div><small>Correções em aberto</small><strong><?=(int)$openCorrections?></strong></div><div><small>Notificações ativas</small><strong><?=(int)$activeNotifications?></strong></div><div><small>Prazo previsto da obra</small><strong><?=htmlspecialchars($work['planned_end'] ?: '-')?></strong></div></div>
<div class="responsible-attention"><?php if($attentionTotal===0):?><span class="ok">Nenhuma ação imediata pendente</span><?php else:?><span><?=$attentionTotal?> item(ns) precisam de atenção</span><?php if($documentCorrection>0):?><span><?=$documentCorrection?> documento(s) para corrigir</span><?php endif;?><?php if($openCorrections>0):?><span><?=$openCorrections?> correção(ões) em aberto</span><?php endif;?><?php endif;?></div>
<div class="portal-actions"><a class="button primary" href="/work/diary?id=<?=(int)$work['id']?>">Ver Diário da Obra</a><?php if($openCorrections>0):?><a class="button secondary" href="/corrections?work=<?=(int)$work['id']?>">Enviar / acompanhar correções</a><?php endif;?></div></section>

<section class="panel" id="documentos"><div class="panel-header"><div><h2>Documentos</h2><p>Envie documentos e acompanhe a análise da administração.</p></div></div><div class="document-list">
<?php foreach($documents as $doc):?><article class="document-row"><div class="document-main"><div><strong><?=htmlspecialchars($doc['name'])?></strong><?php if($doc['required_default']):?><span class="required-tag">Obrigatório</span><?php endif;?></div><p><?=!empty($doc['document_id'])?htmlspecialchars($doc['original_name']).' · v'.(int)$doc['version']:'Nenhum arquivo enviado'?></p><?php if(!empty($doc['review_notes'])):?><div class="review-note"><b>Orientação:</b> <?=nl2br(htmlspecialchars($doc['review_notes']))?></div><?php endif;?></div><div class="document-status"><span class="badge"><?=htmlspecialchars($documentLabels[$doc['status'] ?? 'PENDING'] ?? ($doc['status'] ?? 'Pendente'))?></span></div>
<?php if(!empty($doc['document_id'])):?><div class="inline-actions"><a class="button secondary" target="_blank" href="/work/document?id=<?=(int)$doc['document_id']?>">Abrir arquivo</a></div><?php endif;?>
<?php if($canUpload):?><form class="upload-form" method="post" action="/responsible/document/upload" enctype="multipart/form-data"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="document_type_id" value="<?=(int)$doc['id']?>"><input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required><button type="submit" class="button secondary"><?=!empty($doc['document_id'])?'Enviar nova versão':'Enviar documento'?></button></form><?php endif;?></article><?php endforeach;?>
</div></section>

<section class="panel" id="correcoes"><div class="panel-header"><div><h2>Correções solicitadas</h2><p>Regularize apontamentos e envie evidências para validação do fiscal.</p></div><?php if($corrections):?><a class="button primary" href="/corrections?work=<?=(int)$work['id']?>">Abrir central de correções</a><?php endif;?></div><div class="operation-list">
<?php if(!$corrections):?><div class="empty-state"><p>Nenhuma não conformidade registrada.</p></div><?php endif;?>
<?php foreach($corrections as $item):?><article class="operation-card"><div><div class="row-gap"><strong><?=htmlspecialchars($item['title'])?></strong><span class="badge severity-<?=strtolower($item['severity'])?>"><?=htmlspecialchars($severityLabels[$item['severity']] ?? $item['severity'])?> · <?=htmlspecialchars($item['status'])?></span></div><p><?=nl2br(htmlspecialchars($item['description']))?></p><?php if($item['corrective_deadline']):?><p><b>Prazo:</b> <?=htmlspecialchars(date('d/m/Y H:i',strtotime($item['corrective_deadline'])))?></p><?php endif;?><?php if($item['correction_notes']):?><div class="review-note"><b>Correção informada:</b> <?=nl2br(htmlspecialchars($item['correction_notes']))?></div><?php endif;?></div></article><?php endforeach;?></div></section>

<section class="panel" id="notificacoes"><div class="panel-header"><div><h2>Notificações recebidas</h2><p>Consulte comunicados formais e prazos.</p></div></div><div class="operation-list">
<?php if(!$notifications):?><div class="empty-state"><p>Nenhuma notificação emitida para esta obra.</p></div><?php endif;?>
<?php foreach($notifications as $notification):?><article class="operation-card"><div><div class="row-gap"><strong><?=htmlspecialchars($typeLabels[$notification['type']] ?? $notification['type'])?> · <?=htmlspecialchars($notification['number'])?></strong><span class="badge"><?=htmlspecialchars($notification['status'])?></span></div><p><?=htmlspecialchars($notification['reason'])?></p><?php if($notification['deadline']):?><p><b>Prazo:</b> <?=htmlspecialchars(date('d/m/Y H:i',strtotime($notification['deadline'])))?></p><?php endif;?></div><a class="button secondary" target="_blank" href="/notification/pdf?id=<?=(int)$notification['id']?>">Abrir PDF</a></article><?php endforeach;?></div></section>

<section class="panel" id="conclusao"><div class="panel-header"><div><h2>Conclusão da obra</h2><p>Acompanhe a vistoria final e os documentos finais.</p></div></div>
<?php if($completion):?><div class="info-grid"><div><small>Resultado da vistoria final</small><strong><?=htmlspecialchars($completion['result']==='APPROVED'?'Aprovada':'Correção necessária')?></strong></div><div><small>Fiscal</small><strong><?=htmlspecialchars($completion['inspector_name'])?></strong></div><div><small>Data</small><strong><?=htmlspecialchars($completion['completed_at'] ?: $completion['updated_at'])?></strong></div></div><?php if($completion['result']==='APPROVED'):?><div class="form-actions"><a class="button primary" target="_blank" href="/work/completion/term?id=<?=(int)$work['id']?>">Termo de conclusão</a><a class="button secondary" target="_blank" href="/work/dossier?id=<?=(int)$work['id']?>">Dossiê digital</a></div><?php endif;?><?php else:?><div class="empty-state"><p>A obra ainda não possui vistoria final concluída.</p></div><?php endif;?></section>
</main></div></body></html>
