<?php
use App\Core\Csrf;
$statusLabels=[
'DRAFT'=>'Rascunho','WAITING_DOCUMENTS'=>'Aguardando documentos','UNDER_REVIEW'=>'Em análise','CORRECTION_REQUIRED'=>'Correção necessária','TECHNICALLY_APPROVED'=>'Aprovada tecnicamente','AUTHORIZED'=>'Autorizada','IN_PROGRESS'=>'Em andamento','NOTIFIED'=>'Notificada','SUSPENDED'=>'Suspensa','EMBARGOED'=>'Embargada','COMPLETION_INSPECTION'=>'Vistoria de conclusão','COMPLETED'=>'Concluída','CANCELLED'=>'Cancelada'];
$documentLabels=['SUBMITTED'=>'Enviado','APPROVED'=>'Aprovado','CORRECTION_REQUIRED'=>'Correção necessária','REJECTED'=>'Reprovado','PENDING'=>'Pendente'];
$severityLabels=['LOW'=>'Leve','MEDIUM'=>'Moderada','HIGH'=>'Grave','CRITICAL'=>'Crítica'];
$notificationLabels=['IRREGULARITY'=>'Irregularidade','WARNING'=>'Advertência','ADJUSTMENT'=>'Adequação','SUSPENSION'=>'Suspensão','EMBARGO'=>'Embargo','RELEASE'=>'Liberação'];
$inspectionLabels=['COMPLIANT'=>'Conforme','WITH_ISSUES'=>'Com apontamentos','CRITICAL'=>'Crítica'];
$operational=in_array($work['status'],['IN_PROGRESS','NOTIFIED','SUSPENDED','EMBARGOED'],true);
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Obra <?=htmlspecialchars($work['unit'])?></title><link rel="stylesheet" href="/assets/css/app.css"></head>
<body class="app-body"><div class="shell">
<aside class="sidebar"><div class="brand">Fiscaliza Obras</div><nav><a href="/">Visão geral</a><a class="active" href="/works?condo=<?=(int)$work['condominium_id']?>">Obras</a><a href="#documentos">Documentos</a><a href="#fiscalizacoes">Fiscalizações</a><a href="#correcoes">Correções</a><a href="#notificacoes">Notificações</a><a href="#historico">Histórico</a><?php if($canInspect):?><a href="/settings?condo=<?=(int)$work['condominium_id']?>">Painel do Fiscal</a><?php endif;?></nav></aside>
<main class="content">
<header class="topbar"><div><p class="eyebrow"><?=htmlspecialchars($work['condominium_name'])?></p><h1>Unidade <?=htmlspecialchars($work['unit'])?></h1><p class="muted"><?=htmlspecialchars($work['work_type']?:'Obra')?> · <?=htmlspecialchars($statusLabels[$work['status']]??$work['status'])?></p></div><a class="button secondary" href="/works?condo=<?=(int)$work['condominium_id']?>">← Voltar</a></header>

<?php if(isset($_GET['uploaded'])):?><div class="alert success">Documento enviado com sucesso.</div><?php endif;?>
<?php if(isset($_GET['reviewed'])):?><div class="alert success">Análise do documento registrada.</div><?php endif;?>
<?php if(isset($_GET['status'])):?><div class="alert success">Status da obra atualizado.</div><?php endif;?>
<?php if(isset($_GET['inspection'])):?><div class="alert success">Fiscalização registrada com sucesso.</div><?php endif;?>
<?php if(isset($_GET['nc'])):?><div class="alert success">Não conformidade registrada. Ação sugerida: <?=htmlspecialchars($_GET['suggested']??'NONE')?>.</div><?php endif;?>
<?php if(isset($_GET['notification'])):?><div class="alert success">Notificação emitida com sucesso.</div><?php endif;?>
<?php if(isset($_GET['invite'])):?><div class="alert success">Convite gerado. Envie o link abaixo ao responsável pela obra.</div><?php endif;?>
<?php if(!empty($_GET['invite_url'])):?><section class="panel"><h2>Link de acesso do responsável</h2><p class="muted">Válido por 72 horas e de uso único.</p><div class="description-box" style="word-break:break-all"><?=htmlspecialchars(urldecode((string)$_GET['invite_url']))?></div></section><?php endif;?>

<section class="panel"><div class="panel-header"><div><h2>Ações rápidas</h2><p>Atalhos para os principais fluxos desta obra.</p></div><span class="badge"><?=htmlspecialchars($statusLabels[$work['status']]??$work['status'])?></span></div><div class="inline-actions">
<?php if($canInspect&&$operational):?><a class="button primary" href="/inspection/new?work=<?=(int)$work['id']?>">Nova fiscalização</a><?php endif;?>
<a class="button secondary" href="/corrections?work=<?=(int)$work['id']?>">Correções</a>
<?php if(in_array($work['status'],['IN_PROGRESS','NOTIFIED','COMPLETION_INSPECTION','COMPLETED'],true)):?><a class="button secondary" href="/work/completion?id=<?=(int)$work['id']?>">Conclusão</a><?php endif;?>
<?php if($work['status']==='COMPLETED'):?><a class="button secondary" target="_blank" href="/work/dossier?id=<?=(int)$work['id']?>">Dossiê digital</a><?php endif;?>
<?php if($canInspect):?><a class="button secondary" href="/settings?condo=<?=(int)$work['condominium_id']?>">Configurar fiscalização</a><?php endif;?>
</div></section>

<div class="detail-grid"><section class="panel"><div class="panel-header"><div><h2>Dados da obra</h2><p>Informações principais cadastradas.</p></div></div><div class="info-grid"><div><small>Proprietário</small><strong><?=htmlspecialchars($work['owner_name'])?></strong><span><?=htmlspecialchars($work['owner_phone']?:'-')?></span></div><div><small>Empresa</small><strong><?=htmlspecialchars($work['company_name']?:'-')?></strong><span><?=htmlspecialchars($work['company_phone']?:'-')?></span></div><div><small>Responsável técnico</small><strong><?=htmlspecialchars($work['technical_name']?:'-')?></strong><span><?=htmlspecialchars($work['technical_registry']?:'-')?></span></div><div><small>Período previsto</small><strong><?=htmlspecialchars($work['planned_start']?:'-')?> → <?=htmlspecialchars($work['planned_end']?:'-')?></strong></div></div><?php if($work['description']):?><div class="description-box"><?=nl2br(htmlspecialchars($work['description']))?></div><?php endif;?></section>
<section class="panel actions-panel"><h2>Etapa documental</h2><?php if($canReview&&in_array($work['status'],['WAITING_DOCUMENTS','UNDER_REVIEW','CORRECTION_REQUIRED'],true)):?><form method="post" action="/work/transition"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="target_status" value="TECHNICALLY_APPROVED"><button class="button primary">Aprovar tecnicamente</button></form><?php endif;?><?php if($canAuthorize&&$work['status']==='TECHNICALLY_APPROVED'):?><form method="post" action="/work/transition"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="target_status" value="AUTHORIZED"><button class="button primary">Autorizar início</button></form><?php endif;?><?php if($canAuthorize&&$work['status']==='AUTHORIZED'):?><form method="post" action="/work/transition"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="target_status" value="IN_PROGRESS"><button class="button primary">Registrar início da obra</button></form><?php endif;?></section></div>

<section class="panel" id="documentos"><div class="panel-header"><div><h2>Documentos</h2><p>Versões, análise e acesso seguro aos arquivos.</p></div></div><div class="document-list">
<?php foreach($documents as $doc):?><article class="document-row"><div class="document-main"><div><strong><?=htmlspecialchars($doc['name'])?></strong><?php if($doc['required_default']):?><span class="required-tag">Obrigatório</span><?php endif;?></div><p><?=$doc['document_id']?htmlspecialchars($doc['original_name']).' · v'.(int)$doc['version']:'Nenhum arquivo enviado'?></p><?php if($doc['review_notes']):?><div class="review-note"><?=nl2br(htmlspecialchars($doc['review_notes']))?></div><?php endif;?></div><div class="document-status"><span class="badge"><?=htmlspecialchars($documentLabels[$doc['status']??'PENDING']??($doc['status']??'Pendente'))?></span></div>
<?php if($doc['document_id']):?><a class="button secondary" target="_blank" href="/work/document?id=<?=(int)$doc['document_id']?>">Abrir</a><?php endif;?>
<?php if($canUpload):?><form class="upload-form" method="post" action="/work/document/upload" enctype="multipart/form-data"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="document_type_id" value="<?=(int)$doc['id']?>"><input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required><button class="button secondary"><?=$doc['document_id']?'Nova versão':'Enviar'?></button></form><?php endif;?>
<?php if($canReview&&$doc['document_id']&&$doc['status']==='SUBMITTED'):?><form class="review-form" method="post" action="/work/document/review"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><input type="hidden" name="document_id" value="<?=(int)$doc['document_id']?>"><textarea name="review_notes" placeholder="Observação da análise"></textarea><div class="review-actions"><button name="decision" value="APPROVED" class="button primary">Aprovar</button><button name="decision" value="CORRECTION_REQUIRED" class="button warning">Pedir correção</button><button name="decision" value="REJECTED" class="button danger">Reprovar</button></div></form><?php endif;?></article><?php endforeach;?></div></section>

<section class="panel" id="fiscalizacoes"><div class="panel-header"><div><h2>Fiscalizações</h2><p>As novas vistorias usam o checklist configurado especificamente para este condomínio.</p></div><?php if($canInspect&&$operational):?><a class="button primary" href="/inspection/new?work=<?=(int)$work['id']?>">+ Nova fiscalização</a><?php endif;?></div><div class="operation-list"><?php if(!$inspections):?><div class="empty-state"><p>Nenhuma fiscalização registrada.</p></div><?php endif;?><?php foreach($inspections as $inspection):?><article class="operation-card"><div><strong>Vistoria #<?=(int)$inspection['id']?> · <?=htmlspecialchars($inspectionLabels[$inspection['result']]??$inspection['result'])?></strong><small><?=htmlspecialchars($inspection['inspector_name'])?> · <?=htmlspecialchars($inspection['inspected_at'])?></small><?php if($inspection['stage']):?><p><b>Etapa:</b> <?=htmlspecialchars($inspection['stage'])?></p><?php endif;?><?php if($inspection['notes']):?><p><?=nl2br(htmlspecialchars($inspection['notes']))?></p><?php endif;?></div><a class="button secondary" href="/inspection/photos?id=<?=(int)$inspection['id']?>">Fotos e evidências</a></article><?php endforeach;?></div></section>

<section class="panel" id="correcoes"><div class="panel-header"><div><h2>Não conformidades</h2><p>Apontamentos, prazos e validação das correções.</p></div><a class="button secondary" href="/corrections?work=<?=(int)$work['id']?>">Central de correções</a></div>
<?php if($canInspect&&$operational):?><form class="form-stack operation-form" method="post" action="/work/non-conformity/create"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><div class="form-grid"><label>Fiscalização vinculada<select name="inspection_id"><option value="">Sem vínculo</option><?php foreach($inspections as $inspection):?><option value="<?=(int)$inspection['id']?>">#<?=(int)$inspection['id']?> · <?=htmlspecialchars($inspection['stage']?:'Fiscalização')?></option><?php endforeach;?></select></label><label>Gravidade<select name="severity"><option value="LOW">Leve</option><option value="MEDIUM">Moderada</option><option value="HIGH">Grave</option><option value="CRITICAL">Crítica</option></select></label><label>Título<input name="title" required></label><label>Prazo para correção<input type="datetime-local" name="corrective_deadline"></label><label class="full">Descrição<textarea name="description" rows="3" required></textarea></label></div><div class="form-actions"><button>Registrar não conformidade</button></div></form><?php endif;?>
<div class="operation-list"><?php if(!$nonConformities):?><div class="empty-state"><p>Nenhuma não conformidade registrada.</p></div><?php endif;?><?php foreach($nonConformities as $nc):?><article class="operation-card"><div><div class="row-gap"><strong><?=htmlspecialchars($nc['title'])?></strong><span class="badge severity-<?=strtolower($nc['severity'])?>"><?=htmlspecialchars($severityLabels[$nc['severity']]??$nc['severity'])?> · <?=htmlspecialchars($nc['status'])?></span></div><small><?=htmlspecialchars($nc['creator_name'])?> · <?=htmlspecialchars($nc['created_at'])?></small><p><?=nl2br(htmlspecialchars($nc['description']))?></p><?php if($nc['corrective_deadline']):?><p><b>Prazo:</b> <?=htmlspecialchars($nc['corrective_deadline'])?></p><?php endif;?></div></article><?php endforeach;?></div></section>

<section class="panel" id="notificacoes"><div class="panel-header"><div><h2>Notificações</h2><p>Advertências e adequações não mudam o status da obra; suspensão, embargo e liberação alteram.</p></div></div>
<?php if($canNotify&&$operational):?><form class="form-stack operation-form" method="post" action="/work/notification/create"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><div class="form-grid"><label>Tipo<select name="type"><option value="IRREGULARITY">Irregularidade</option><option value="WARNING">Advertência</option><option value="ADJUSTMENT">Solicitação de adequação</option><?php if($canRestrictWork):?><option value="SUSPENSION">Suspensão</option><option value="EMBARGO">Embargo</option><option value="RELEASE">Liberação</option><?php endif;?></select></label><label>Prazo<input type="datetime-local" name="deadline"></label><label class="full">Motivo<input name="reason" placeholder="Deixe em branco para usar o modelo padrão"></label><label class="full">Texto<textarea name="body" rows="4" placeholder="Deixe em branco para usar o modelo padrão"></textarea></label></div><div class="form-actions"><button>Emitir notificação</button></div></form><?php endif;?>
<div class="operation-list"><?php if(!$notifications):?><div class="empty-state"><p>Nenhuma notificação emitida.</p></div><?php endif;?><?php foreach($notifications as $notification):?><article class="operation-card"><div><div class="row-gap"><strong><?=htmlspecialchars($notificationLabels[$notification['type']]??$notification['type'])?> · <?=htmlspecialchars($notification['number'])?></strong><span class="badge"><?=htmlspecialchars($notification['status'])?></span></div><small><?=htmlspecialchars($notification['creator_name'])?> · <?=htmlspecialchars($notification['created_at'])?></small><p><b><?=htmlspecialchars($notification['reason'])?></b></p><?php if($notification['deadline']):?><p><b>Prazo:</b> <?=htmlspecialchars($notification['deadline'])?></p><?php endif;?></div><a class="button secondary" target="_blank" href="/notification/pdf?id=<?=(int)$notification['id']?>">PDF</a></article><?php endforeach;?></div></section>

<?php if($canAuthorize):?><section class="panel"><div class="panel-header"><div><h2>Acesso do responsável pela obra</h2><p>Gere um convite de uso único, válido por 72 horas.</p></div></div><form method="post" action="/work/invite" class="form-stack"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="work_id" value="<?=(int)$work['id']?>"><div class="form-grid"><label>E-mail do responsável<input type="email" name="email" value="<?=htmlspecialchars($work['owner_email']?:'')?>" required></label></div><div class="form-actions"><button class="button primary">Gerar convite</button></div></form></section><?php endif;?>

<section class="panel" id="historico"><div class="panel-header"><div><h2>Histórico da obra</h2><p>Eventos operacionais registrados pelo sistema.</p></div></div><div class="timeline"><?php if(!$events):?><div class="empty-state"><p>Nenhum evento registrado.</p></div><?php endif;?><?php foreach($events as $event):?><article class="timeline-item"><span></span><div><strong><?=htmlspecialchars($event['title'])?></strong><small><?=htmlspecialchars($event['user_name']?:'Sistema')?> · <?=htmlspecialchars($event['created_at'])?></small><?php if($event['description']):?><p><?=nl2br(htmlspecialchars($event['description']))?></p><?php endif;?></div></article><?php endforeach;?></div></section>
</main></div></body></html>
