<?php
$statusLabels=['WAITING_DOCUMENTS'=>'Aguardando documentos','UNDER_REVIEW'=>'Em análise','CORRECTION_REQUIRED'=>'Correção necessária','TECHNICALLY_APPROVED'=>'Aprovada tecnicamente','AUTHORIZED'=>'Autorizada','IN_PROGRESS'=>'Em andamento','NOTIFIED'=>'Notificada','SUSPENDED'=>'Suspensa','EMBARGOED'=>'Embargada','COMPLETION_INSPECTION'=>'Vistoria final','COMPLETED'=>'Concluída'];
$sidebarCondoId=(int)$condoId;
$sidebarActive='reports';
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatórios · Fiscaliza Obras</title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/ui-v2.css"></head><body class="app-body"><div class="shell"><?php require __DIR__ . '/resources_sidebar.php'; ?><main class="content"><header class="topbar"><div><p class="eyebrow">Gestão e indicadores</p><h1>Relatórios de obras</h1><p class="muted">Visão consolidada por condomínio, situação, prazos e pendências operacionais.</p></div></header>
<section class="panel"><form method="get" action="/reports" class="form-grid"><label>Condomínio<select name="condo"><option value="">Todos</option><?php foreach($condos as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $condoId===(int)$c['id']?'selected':'' ?>><?= htmlspecialchars($c['name']) ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="">Todos</option><?php foreach($statusLabels as $code=>$label): ?><option value="<?= htmlspecialchars($code) ?>" <?= $status===$code?'selected':'' ?>><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select></label><div class="form-actions"><button class="button primary">Filtrar</button><a class="button secondary" href="/reports<?= $condoId ? '?condo='.(int)$condoId : '' ?>">Limpar</a></div></form></section>

<div class="stats-grid report-stats">
<article class="stat-card"><span>Total de obras</span><strong><?= (int)($kpis['total']??0) ?></strong></article>
<article class="stat-card"><span>Operacionais</span><strong><?= (int)($kpis['operational']??0) ?></strong></article>
<article class="stat-card"><span>Concluídas</span><strong><?= (int)($kpis['completed']??0) ?></strong></article>
<article class="stat-card"><span>Obras atrasadas</span><strong><?= (int)($kpis['overdue']??0) ?></strong></article>
<article class="stat-card"><span>NCs abertas</span><strong><?= (int)($kpis['open_nc_total']??0) ?></strong></article>
<article class="stat-card"><span>Fiscalizações</span><strong><?= (int)($kpis['inspections_total']??0) ?></strong></article>
<article class="stat-card"><span>Notificações</span><strong><?= (int)($kpis['notifications_total']??0) ?></strong></article>
<article class="stat-card"><span>Suspensas / Embargadas</span><strong><?= (int)($kpis['suspended']??0)+(int)($kpis['embargoed']??0) ?></strong></article>
</div>

<section class="panel"><div class="panel-header"><div><h2>Distribuição por status</h2><p>Quantidade de obras em cada etapa do fluxo.</p></div></div><?php if(!$statusBreakdown):?><div class="empty-state"><p>Sem dados para o filtro atual.</p></div><?php else:?><div class="status-breakdown-grid"><?php foreach($statusBreakdown as $item):?><div class="status-breakdown-item"><span><?=htmlspecialchars($statusLabels[$item['status']]??$item['status'])?></span><strong><?=(int)$item['total']?></strong></div><?php endforeach;?></div><?php endif;?></section>

<section class="panel"><div class="panel-header"><div><h2>Obras</h2><p><?= count($works) ?> registro(s) no filtro atual.</p></div></div><?php if(!$works): ?><div class="empty-state"><p>Nenhuma obra encontrada.</p></div><?php else: ?><div class="table-wrap"><table><thead><tr><th>Condomínio</th><th>Unidade</th><th>Tipo</th><th>Status</th><th>Prazo</th><th>Pendências</th><th>Fiscalizações</th><th>Notificações</th><th>Ações</th></tr></thead><tbody><?php foreach($works as $w): ?><tr class="<?=$w['overdue']?'row-overdue':''?>"><td><?= htmlspecialchars($w['condominium_name']) ?><small class="table-subline"><?=htmlspecialchars($w['owner_name'])?></small></td><td><?= htmlspecialchars($w['unit']) ?></td><td><?=htmlspecialchars($w['work_type']?:'-')?></td><td><span class="badge"><?= htmlspecialchars($statusLabels[$w['status']]??$w['status']) ?></span><?php if($w['overdue']):?><span class="late-pill">Atrasada</span><?php endif;?></td><td><?=htmlspecialchars($w['planned_end']?:'-')?></td><td><?= (int)$w['open_nc'] ?></td><td><?= (int)$w['inspections_count'] ?></td><td><?= (int)$w['notifications_count'] ?></td><td><div class="inline-actions"><a class="button secondary" href="/work?id=<?= (int)$w['id'] ?>">Abrir</a><?php if(in_array($w['status'],['IN_PROGRESS','NOTIFIED','COMPLETION_INSPECTION','COMPLETED'],true)):?><a class="button secondary" href="/work/completion?id=<?= (int)$w['id'] ?>">Conclusão</a><?php endif;?><?php if($w['status']==='COMPLETED'):?><a class="button secondary" href="/work/dossier?id=<?= (int)$w['id'] ?>" target="_blank">Dossiê final</a><?php endif;?></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section></main></div></body></html>
