<?php
use App\Core\Csrf;
$defaults=[
'default_notification_days'=>(int)($rules['default_notification_days']??5),
'warning_days'=>(int)($rules['warning_days']??3),
'adjustment_days'=>(int)($rules['adjustment_days']??5),
'suspension_days'=>(int)($rules['suspension_days']??0),
'embargo_days'=>(int)($rules['embargo_days']??0),
];
$typeLabels=['IRREGULARITY'=>'Irregularidade','WARNING'=>'Advertência','ADJUSTMENT'=>'Adequação','SUSPENSION'=>'Suspensão','EMBARGO'=>'Embargo','RELEASE'=>'Liberação'];
$templateMap=[]; foreach($templates as $t){$templateMap[$t['type']]=$t;}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Configurações · <?=htmlspecialchars($condo['name'])?></title><link rel="stylesheet" href="/assets/css/app.css"></head><body class="app-body"><div class="shell"><aside class="sidebar"><div class="brand">Fiscaliza Obras</div><nav><a href="/">Visão geral</a><a href="/works?condo=<?=(int)$condo['id']?>">Obras</a><a href="/reports?condo=<?=(int)$condo['id']?>">Relatórios</a><a class="active" href="/settings?condo=<?=(int)$condo['id']?>">Configurações</a></nav></aside><main class="content"><header class="topbar"><div><p class="eyebrow">Painel do Fiscal</p><h1><?=htmlspecialchars($condo['name'])?></h1><p class="muted">Regras, prazos, modelos e checklist deste condomínio.</p></div></header>
<?php if(isset($_GET['saved'])||isset($_GET['template'])||isset($_GET['checklist'])):?><div class="alert success">Configuração salva com sucesso.</div><?php endif;?>
<section class="panel"><div class="panel-header"><div><h2>Regras gerais</h2><p>Prazos e exigências padrão do condomínio.</p></div></div><form method="post" action="/settings/rules" class="form-stack"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="condo_id" value="<?=(int)$condo['id']?>"><div class="form-grid"><label>Prazo padrão de notificação (dias)<input type="number" min="0" name="default_notification_days" value="<?=$defaults['default_notification_days']?>"></label><label>Prazo de advertência (dias)<input type="number" min="0" name="warning_days" value="<?=$defaults['warning_days']?>"></label><label>Prazo de adequação (dias)<input type="number" min="0" name="adjustment_days" value="<?=$defaults['adjustment_days']?>"></label><label>Prazo de suspensão (dias)<input type="number" min="0" name="suspension_days" value="<?=$defaults['suspension_days']?>"></label><label>Prazo de embargo (dias)<input type="number" min="0" name="embargo_days" value="<?=$defaults['embargo_days']?>"></label></div><div class="check-grid"><label><input type="checkbox" name="require_photo_on_inspection" value="1" <?=!empty($rules['require_photo_on_inspection'])?'checked':''?>> Exigir foto na fiscalização</label><label><input type="checkbox" name="require_photo_on_non_conformity" value="1" <?=!empty($rules['require_photo_on_non_conformity'])?'checked':''?>> Exigir foto em não conformidade</label><label><input type="checkbox" name="require_final_inspection" value="1" <?=array_key_exists('require_final_inspection',$rules)?(!empty($rules['require_final_inspection'])?'checked':''):'checked'?>> Exigir vistoria final</label><label><input type="checkbox" name="block_completion_with_open_nc" value="1" <?=array_key_exists('block_completion_with_open_nc',$rules)?(!empty($rules['block_completion_with_open_nc'])?'checked':''):'checked'?>> Bloquear conclusão com NC aberta</label><label><input type="checkbox" name="allow_inspector_warning" value="1" <?=array_key_exists('allow_inspector_warning',$rules)?(!empty($rules['allow_inspector_warning'])?'checked':''):'checked'?>> Fiscal pode emitir advertência</label><label><input type="checkbox" name="allow_inspector_adjustment" value="1" <?=array_key_exists('allow_inspector_adjustment',$rules)?(!empty($rules['allow_inspector_adjustment'])?'checked':''):'checked'?>> Fiscal pode solicitar adequação</label></div><div class="form-actions"><button type="submit">Salvar regras</button></div></form></section>
<section class="panel"><div class="panel-header"><div><h2>Modelos de notificação</h2><p>Texto e prazo sugeridos para cada tipo.</p></div></div><div class="operation-list"><?php foreach($typeLabels as $type=>$label):$t=$templateMap[$type]??[];?><form method="post" action="/settings/template" class="operation-card"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="condo_id" value="<?=(int)$condo['id']?>"><input type="hidden" name="type" value="<?=htmlspecialchars($type)?>"><div class="form-grid"><label>Tipo<input value="<?=htmlspecialchars($label)?>" disabled></label><label>Título<input name="title" required value="<?=htmlspecialchars($t['title']??$label)?>"></label><label>Prazo padrão (dias)<input type="number" min="0" name="default_deadline_days" value="<?=(int)($t['default_deadline_days']??0)?>"></label><label class="full">Motivo padrão<input name="default_reason" value="<?=htmlspecialchars($t['default_reason']??'')?>"></label><label class="full">Texto padrão<textarea name="default_body" rows="4"><?=htmlspecialchars($t['default_body']??'')?></textarea></label></div><label><input type="checkbox" name="active" value="1" <?=!isset($t['active'])||$t['active']?'checked':''?>> Modelo ativo</label><div class="form-actions"><button type="submit">Salvar <?=htmlspecialchars($label)?></button></div></form><?php endforeach;?></div></section>
<section class="panel"><div class="panel-header"><div><h2>Checklist de fiscalização</h2><p>Itens adicionais específicos deste condomínio.</p></div></div><form method="post" action="/settings/checklist" class="form-stack"><input type="hidden" name="_token" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="condo_id" value="<?=(int)$condo['id']?>"><div class="form-grid"><label>Item<input name="label" required placeholder="Ex.: Proteção do elevador"></label><label>Categoria<input name="category" placeholder="Ex.: Áreas comuns"></label><label>Ordem<input type="number" name="sort_order" value="0"></label></div><label><input type="checkbox" name="required" value="1"> Item obrigatório</label><div class="form-actions"><button type="submit">Adicionar item</button></div></form><div class="operation-list"><?php if(!$checklist):?><div class="empty-state"><p>Nenhum item personalizado ainda.</p></div><?php endif;?><?php foreach($checklist as $item):?><article class="operation-card"><strong><?=htmlspecialchars($item['label'])?></strong><small><?=htmlspecialchars($item['category']??'Sem categoria')?> · <?=$item['required']?'Obrigatório':'Opcional'?> · <?=$item['active']?'Ativo':'Inativo'?></small></article><?php endforeach;?></div></section>
</main></div></body></html>