<?php
use App\Core\Csrf;
$sidebarCondoId=(int)$work['condominium_id'];
$sidebarWorkId=(int)$inspection['work_id'];
$sidebarWorkStatus=(string)($work['status']??'');
$sidebarRoles=$work['_roles']??[];
$sidebarActive='inspections';
?>
<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fotos da fiscalização</title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/media.css"><link rel="stylesheet" href="/assets/css/ui-v2.css"></head>
<body class="app-body"><div class="shell"><?php require __DIR__ . '/resources_sidebar.php'; ?><main class="content"><header class="topbar"><div><p class="eyebrow"><?= htmlspecialchars($work['condominium_name']) ?></p><h1>Fotos da fiscalização #<?= (int)$inspection['id'] ?></h1><p class="muted">Unidade <?= htmlspecialchars($inspection['unit']) ?><?= $inspection['stage'] ? ' · ' . htmlspecialchars($inspection['stage']) : '' ?></p></div><a class="button secondary" href="/work?id=<?= (int)$inspection['work_id'] ?>">← Voltar à obra</a></header><?php if (isset($_GET['uploaded'])): ?><div class="alert success">Foto adicionada com sucesso.</div><?php endif; ?><?php if ($canUploadPhoto): ?><section class="panel"><div class="panel-header"><div><h2>Adicionar evidência</h2><p>JPG, PNG ou WEBP de até 8 MB.</p></div></div><form method="post" action="/inspection/photo/upload" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><input type="hidden" name="inspection_id" value="<?= (int)$inspection['id'] ?>"><label>Foto<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label><label>Legenda<input name="caption" maxlength="255" placeholder="Ex.: proteção do elevador"></label><div class="full form-actions"><button type="submit">Adicionar foto</button></div></form></section><?php endif; ?><section class="panel"><div class="panel-header"><div><h2>Evidências registradas</h2><p><?= count($photos) ?> foto(s) vinculada(s) a esta fiscalização.</p></div></div><?php if (!$photos): ?><div class="empty-state">Nenhuma foto registrada.</div><?php else: ?><div class="photo-grid"><?php foreach ($photos as $photo): ?><article class="photo-card"><a href="/inspection/photo?id=<?= (int)$photo['id'] ?>" target="_blank" rel="noopener"><img src="/inspection/photo?id=<?= (int)$photo['id'] ?>" alt="<?= htmlspecialchars($photo['caption'] ?: 'Foto da fiscalização') ?>"></a><div><strong><?= htmlspecialchars($photo['caption'] ?: $photo['original_name']) ?></strong><small><?= htmlspecialchars($photo['uploaded_by_name'] ?? 'Usuário') ?> · <?= htmlspecialchars($photo['created_at']) ?></small></div></article><?php endforeach; ?></div><?php endif; ?></section></main></div></body></html>
