<?php use App\Core\Csrf; ?>
<!doctype html>
<html lang="pt-BR">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Conclusão da obra</title><link rel="stylesheet" href="/assets/css/app.css"></head>
<body class="app-body"><div class="shell"><aside class="sidebar"><div class="brand">Fiscaliza Obras</div><nav><a href="/">Visão geral</a><a href="/works?condo=<?= (int)$work['condominium_id'] ?>">Obras</a><a class="active" href="/work/completion?id=<?= (int)$work['id'] ?>">Conclusão</a><a href="/reports?condo=<?= (int)$work['condominium_id'] ?>">Relatórios</a></nav></aside><main class="content"><header class="topbar"><div><p class="eyebrow"><?= htmlspecialchars($work['condominium_name']) ?></p><h1>Conclusão · Unidade <?= htmlspecialchars($work['unit']) ?></h1><p class="muted">Status atual: <?= htmlspecialchars($work['status']) ?></p></div><a class="button secondary" href="/work?id=<?= (int)$work['id'] ?>">← Voltar à obra</a></header>
<?php if (isset($_GET['started'])): ?><div class="alert success">Vistoria final iniciada.</div><?php endif; ?>
<?php if (isset($_GET['recorded'])): ?><div class="alert success">Resultado da vistoria final registrado.</div><?php endif; ?>
<section class="panel"><div class="panel-header"><div><h2>Condições para encerramento</h2><p>A obra só pode ser concluída sem não conformidades abertas.</p></div></div><div class="info-grid"><div><small>Não conformidades abertas</small><strong><?= (int)$openNc ?></strong></div><div><small>Proprietário</small><strong><?= htmlspecialchars($work['owner_name']) ?></strong></div><div><small>Tipo</small><strong><?= htmlspecialchars($work['work_type'] ?: '-') ?></strong></div><div><small>Status</small><strong><?= htmlspecialchars($work['status']) ?></strong></div></div></section>
<?php if ($canStart): ?><section class="panel"><h2>Solicitar vistoria final</h2><p>Ao iniciar, o status da obra mudará para “Vistoria de conclusão”.</p><form method="post" action="/work/completion/start"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><button class="button primary">Iniciar vistoria final</button></form></section><?php endif; ?>
<?php if ($canRecord): ?><section class="panel"><h2>Registrar resultado</h2><form method="post" action="/work/completion/record" class="form-stack"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><label>Resultado<select name="result" required><option value="APPROVED">Aprovada para conclusão</option><option value="CORRECTION_REQUIRED">Correção necessária</option></select></label><label>Observações<textarea name="notes" rows="5" placeholder="Descreva o resultado da vistoria final"></textarea></label><div class="form-actions"><button class="button primary">Salvar resultado</button></div></form></section><?php endif; ?>
<?php if ($completion): ?><section class="panel"><div class="panel-header"><div><h2>Último resultado da vistoria final</h2><p><?= htmlspecialchars($completion['inspector_name']) ?> · <?= htmlspecialchars($completion['updated_at']) ?></p></div><span class="badge"><?= htmlspecialchars($completion['result']) ?></span></div><?php if ($completion['notes']): ?><div class="description-box"><?= nl2br(htmlspecialchars($completion['notes'])) ?></div><?php endif; ?><div class="inline-actions" style="margin-top:16px"><a class="button secondary" href="/work/completion/term?id=<?= (int)$work['id'] ?>" target="_blank">Termo de conclusão PDF</a><a class="button secondary" href="/work/dossier?id=<?= (int)$work['id'] ?>" target="_blank">Dossiê digital PDF</a></div></section><?php endif; ?>
</main></div></body></html>
