<?php
use App\Core\Csrf;
$sidebarCondoId=(int)$work['condominium_id'];
$sidebarWorkId=(int)$work['id'];
$sidebarWorkStatus=(string)($work['status']??'');
$sidebarRoles=$work['_roles']??[];
$sidebarActive='completion';
?>
<!doctype html>
<html lang="pt-BR">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Conclusão da obra</title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/ui-v2.css"></head>
<body class="app-body"><div class="shell"><?php require __DIR__ . '/resources_sidebar.php'; ?><main class="content"><header class="topbar"><div><p class="eyebrow"><?= htmlspecialchars($work['condominium_name']) ?></p><h1>Conclusão · Unidade <?= htmlspecialchars($work['unit']) ?></h1><p class="muted">Status atual: <?= htmlspecialchars($work['status']) ?></p></div><a class="button secondary" href="/work?id=<?= (int)$work['id'] ?>">← Voltar à obra</a></header>
<?php if (isset($_GET['started'])): ?><div class="alert success">Vistoria final iniciada.</div><?php endif; ?>
<?php if (isset($_GET['recorded'])): ?><div class="alert success">Conclusão da obra atualizada.</div><?php endif; ?>
<section class="panel"><div class="panel-header"><div><h2>Condições para encerramento</h2><p>As regras abaixo vêm do Painel do Fiscal deste condomínio.</p></div></div><div class="info-grid"><div><small>Pendências ainda não encerradas</small><strong><?= (int)$openNc ?></strong></div><div><small>Vistoria final</small><strong><?= $requiresFinalInspection ? 'Obrigatória' : 'Dispensada' ?></strong></div><div><small>Bloqueio por pendência</small><strong><?= $blockWithOpenNc ? 'Ativo' : 'Desativado' ?></strong></div><div><small>Proprietário</small><strong><?= htmlspecialchars($work['owner_name']) ?></strong></div><div><small>Tipo</small><strong><?= htmlspecialchars($work['work_type'] ?: '-') ?></strong></div><div><small>Status</small><strong><?= htmlspecialchars($work['status']) ?></strong></div></div><?php if ($blockedByNc): ?><div class="alert error" style="margin-top:16px">A conclusão está bloqueada porque existem pendências ainda não encerradas.</div><?php endif; ?></section>
<?php if ($canStart): ?><section class="panel"><h2>Vistoria final</h2><p>Ao iniciar, o status da obra mudará para “Vistoria de conclusão”.</p><form method="post" action="/work/completion/start"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><button class="button primary">Iniciar vistoria final</button></form></section><?php endif; ?>
<?php if ($canCompleteDirectly): ?><section class="panel"><h2>Conclusão administrativa</h2><p>Este condomínio dispensou a vistoria final. A administração pode concluir a obra diretamente, desde que as demais regras sejam atendidas.</p><form method="post" action="/work/completion/direct" class="form-stack"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><label>Observações<textarea name="notes" rows="4" placeholder="Observação opcional sobre a conclusão"></textarea></label><div class="form-actions"><button class="button primary">Concluir obra</button></div></form></section><?php endif; ?>
<?php if ($canRecord): ?><section class="panel"><h2>Registrar resultado da vistoria</h2><form method="post" action="/work/completion/record" class="form-stack"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><label>Resultado<select name="result" required><option value="APPROVED">Aprovada para conclusão</option><option value="CORRECTION_REQUIRED">Correção necessária</option></select></label><label>Observações<textarea name="notes" rows="5" placeholder="Descreva o resultado da vistoria final"></textarea></label><div class="form-actions"><button class="button primary">Salvar resultado</button></div></form></section><?php endif; ?>
<?php if ($completion): ?><section class="panel"><div class="panel-header"><div><h2>Último resultado de conclusão</h2><p><?= htmlspecialchars($completion['inspector_name']) ?> · <?= htmlspecialchars($completion['updated_at']) ?></p></div><span class="badge"><?= htmlspecialchars($completion['result']) ?></span></div><?php if ($completion['notes']): ?><div class="description-box"><?= nl2br(htmlspecialchars($completion['notes'])) ?></div><?php endif; ?><?php if ($completion['result'] === 'APPROVED'): ?><div class="inline-actions" style="margin-top:16px"><a class="button secondary" href="/work/completion/term?id=<?= (int)$work['id'] ?>" target="_blank">Termo de conclusão PDF</a><a class="button secondary" href="/work/dossier?id=<?= (int)$work['id'] ?>" target="_blank">Dossiê digital PDF</a></div><?php endif; ?></section><?php endif; ?>
</main></div></body></html>
